# See https://fluxcd.io/docs/components/source/gitrepositories/
# and https://github.com/fluxcd/flux2-kustomize-helm-example
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: dummyapp
spec:
  url: https://github.com/stefanprodan/podinfo
  ref:
    branch: master
  interval: 24h
---
apiVersion: apps.kubemate.mgoltzsche.github.com/v1alpha1
kind: App
metadata:
  name: dummyapp
spec:
  kustomization:
    sourceRef:
      kind: GitRepository
      name: dummyapp
    path: ./kustomize
    targetNamespace: kubemate
