apiVersion: apps.kubemate.mgoltzsche.github.com/v1alpha1
kind: App
metadata:
  name: hifiberry-auto-config
spec:
  kustomization:
    sourceRef:
      kind: GitRepository
      name: kubemate-apps
    path: ./config/hifiberry-auto-config
